added pickup and delivery options to inventory
Lambda-School-Labs/PT17_merchant-marketplace-c-fe pull request #6
Opened 2021-04-16 06:51 UTC by lex-marie790

Added the pickup and delivery option to multiple pages related to inventory:
- adding inventory 
- editing inventory 
- item card

2021-04-16 22:48 UTC, karapeoples requested changes
Looks good can you go in and clean up the Tags stuff the linter is saying is assigned but never used. Thank you

2021-04-20 03:43 UTC, karapeoples approved these changes

2021-04-20 03:45 UTC, karapeoples submitted a review, later dismissed
Ty for fixing :)

2021-04-21 00:09 UTC, jonathan-portillo approved these changes
Looks good and seems like you did some clean up on some leftover code .

2021-04-21 00:55 UTC, Brodt7258 approved these changes

2021-04-21 00:55 UTC, merged